options:
  docker: true
  size: 2x
pipelines:
  branches:
    master:
      - step:
          image: google/cloud-sdk:latest
          name: Deploy to production
          deployment: production
          caches:
          - docker
          services:
          - docker
          script:
          # SETUP
          - export IMAGE_NAME=eu.gcr.io/$GCLOUD_PROJECT/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT
          - export ENVIRONMENT=production
          - echo $GCLOUD_API_KEYFILE | base64 -d > ~/.gcloud-api-key.json
          - gcloud auth activate-service-account --key-file ~/.gcloud-api-key.json
          - gcloud config set project $GCLOUD_PROJECT
          - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone=$GCLOUD_ZONE --project $GCLOUD_PROJECT
          - gcloud auth configure-docker --quiet
          # BUILD IMAGE
          - docker build . -t $IMAGE_NAME
          # PUBLISH IMAGE
          - docker push $IMAGE_NAME
          # DEPLOYMENT
          - kubectl set image deployment $BITBUCKET_REPO_SLUG-$ENVIRONMENT $GCLOUD_CONTAINER_NAME=$IMAGE_NAME --record
definitions:
  services:
    docker:
      memory: 7128