# Generated by Django 2.1.3 on 2018-12-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_groups',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
