# Generated by Django 2.1.3 on 2018-12-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_auto_20181203_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
