# Generated by Django 2.2.1 on 2019-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190504_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
