# Generated by Django 2.2.1 on 2019-05-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0012_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_entries',
                                            to='accounts.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ads',
        ),
        migrations.AddField(
            model_name='post',
            name='ads',
            field=models.ManyToManyField(related_name='ads', through='accounts.AdsEntry', to='accounts.Group'),
        ),
        migrations.AddField(
            model_name='adsentry',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_entries',
                                    to='accounts.Post'),
        ),
    ]
