# Generated by Django 2.1.5 on 2019-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
