# Generated by Django 2.2.1 on 2019-05-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('async_tasks', '0003_auto_20190422_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchGroups',
        ),
    ]
