# Generated by Django 2.1.5 on 2019-02-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cheaters.Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rprt', to='cheaters.Entry'),
        ),
    ]
